---
- hosts:
    all

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  collections:
    - azure.azcollection
    - kubernetes.core
    # - brentwg.azure-cli

  tasks:

    - name: Setup Azure credentials
      ansible.builtin.set_fact:
        secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"

    - name: Test az command
      shell: |-
        uname -a
        cat /etc/*-release
        rpm -ivh --nodeps $(curl -Ls -o /dev/null -w %{url_effective} https://aka.ms/InstallAzureCliRpmEdge)

    - name: Test az command
      shell: |-
        az storage account list -o table
