---
- hosts:
    all

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  collections:
    - azure.azcollection
    - kubernetes.core
    # - brentwg.azure-cli

  tasks:

    - name: Setup Azure credentials
      ansible.builtin.set_fact:
        secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"

    - name: Test az command
      shell: |-
        uname -a
        cat /etc/*-release
        sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
        echo -e "[azure-cli]
        name=Azure CLI
        baseurl=https://packages.microsoft.com/yumrepos/azure-cli
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo
        sudo dnf install azure-cli

    - name: Test az command
      shell: |-
        az storage account list -o table
